### PR TITLE
supported thymeleaf 3.x

### PR DESCRIPTION
**Pull request by rline1**
e e e

### CODE REVIEW

**Comment by theborakompanioni** [comment]
@rline1 Nice one! :-)
I will take a look at it in the coming days! 
Thank you!

**Comment by theborakompanioni** [comment]
@rline1 @logemann @opensource21 This pull-request is now merged and released as snapshot (2.0.0-SNAPSHOT). Thanks for your contribution @rline - very much appreciated.

I'll be glad if you continue to report any misbeviour or bugs you encounter.
Thanks for you patience.

**Comment by logemann** [comment]
sorry hadnt the time to look into it. Hopefully can do it in the next days....

**Comment by theborakompanioni** [comment]
@logemann no problem. take your time. thanks :]

ping @saviola777

**Comment by saviola777** [comment]
Thanks, nice work.

**Pull request merged**
